// Code generated by Icestudio 0.10

`default_nettype none

//---- Top entity
module main (
 input [31:0] vbabb27,
 input [31:0] v6c8a4c,
 output [25:0] vc219a6,
 output [31:0] vf2527f,
 output [31:0] va2e910,
 output vc27e51,
 output vac2531,
 output v5b8f0c
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire [0:5] w6;
 wire [0:5] w7;
 wire [0:5] w8;
 wire [0:5] w9;
 wire w10;
 wire w11;
 wire [0:31] w12;
 wire [0:31] w13;
 wire [0:31] w14;
 wire [0:31] w15;
 wire w16;
 wire [0:31] w17;
 wire [0:25] w18;
 wire w19;
 wire w20;
 wire [0:31] w21;
 wire [0:25] w22;
 wire [0:31] w23;
 wire w24;
 wire w25;
 wire w26;
 wire w27;
 wire [0:25] w28;
 wire [0:31] w29;
 wire [0:31] w30;
 wire w31;
 wire [0:31] w32;
 wire [0:25] w33;
 wire [0:31] w34;
 wire [0:31] w35;
 wire [0:25] w36;
 wire [0:31] w37;
 wire w38;
 assign w12 = vbabb27;
 assign vc219a6 = w22;
 assign w23 = v6c8a4c;
 assign vc27e51 = w25;
 assign vac2531 = w26;
 assign v5b8f0c = w27;
 assign vf2527f = w32;
 assign va2e910 = w34;
 assign w11 = w1;
 assign w29 = w13;
 assign w30 = w15;
 assign w32 = w13;
 assign w32 = w29;
 assign w34 = w17;
 assign w35 = w15;
 assign w35 = w30;
 assign w36 = w22;
 v07c3e9 vc2f165 (
  .v9452f7(w0),
  .veae0d5(w1),
  .v733f38(w2),
  .vcf476d(w3),
  .vc2ff47(w4),
  .vefc2f0(w6),
  .v1d4fda(w7),
  .vcc5aff(w8),
  .v9859e3(w9),
  .ve7b995(w10),
  .vd59e62(w18),
  .vf89c40(w19),
  .v37f516(w20),
  .vd56645(w23),
  .v009d23(w31),
  .vd5ffa3(w38)
 );
 v098059 v44d510 (
  .vb9f6e8(w5),
  .v469cec(w22),
  .v64b2fc(w28),
  .ve305d5(w33)
 );
 vd073da v710b38 (
  .v54902b(w0),
  .v333e4c(w1),
  .v394d0e(w2),
  .v708034(w3),
  .v2d8bc3(w4),
  .v7af967(w5),
  .vdf76b1(w16),
  .vc6aa74(w24),
  .vd25d6a(w25),
  .vb561af(w26),
  .vc9a715(w27)
 );
 v51b9cf v9b2244 (
  .vaa5d49(w7),
  .v102134(w8),
  .v14eae6(w9),
  .v7d1d02(w14),
  .vc46106(w15),
  .vfab6dd(w17),
  .v4434b8(w24)
 );
 v625d79 vab0f0a (
  .vcd159e(w6),
  .vea2f6e(w13),
  .v360926(w21),
  .vc8ee55(w37)
 );
 vaa9caf v0ca40e (
  .v604d67(w10),
  .va16ad8(w11),
  .v51b6bc(w12),
  .vcf12e3(w13),
  .va874ad(w14),
  .vbaf620(w33)
 );
 v1215e7 v64a763 (
  .ve0f1d2(w15),
  .va34f84(w16)
 );
 vef4843 v19f6e3 (
  .v3b6447(w17),
  .vb90512(w18),
  .va1f8d5(w19),
  .v301daf(w20),
  .ve4871c(w21)
 );
 v433ce5 v059689 (
  .vbda1cf(w28),
  .v5a59b5(w29),
  .vb6adaf(w30),
  .vf95e96(w31)
 );
 v26af9a v1647fe (
  .v5cb37b(w35),
  .v30c415(w36),
  .v2cf625(w37),
  .vb74a8b(w38)
 );
endmodule

//---- Top entity
module v07c3e9 (
 input [31:0] vd56645,
 output [5:0] v1d4fda,
 output [5:0] vcc5aff,
 output [5:0] v9859e3,
 output [25:0] vd59e62,
 output vf89c40,
 output v37f516,
 output [5:0] vefc2f0,
 output ve7b995,
 output vd5ffa3,
 output v9452f7,
 output veae0d5,
 output v733f38,
 output vcf476d,
 output vc2ff47,
 output v009d23
);

endmodule

//---------------------------------------------------
//-- Instruktionsdekodierer
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- 
//---------------------------------------------------
//---- Top entity
module v098059 (
 input [25:0] v64b2fc,
 input vb9f6e8,
 output [25:0] v469cec,
 output [25:0] ve305d5
);

endmodule

//---------------------------------------------------
//-- Programmzähler
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- 
//---------------------------------------------------
//---- Top entity
module vd073da (
 input vdf76b1,
 input v54902b,
 input v333e4c,
 input v394d0e,
 input v708034,
 input v2d8bc3,
 output vc6aa74,
 output vd25d6a,
 output vb561af,
 output vc9a715,
 output v7af967
);

endmodule

//---------------------------------------------------
//-- Steuerung
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- 
//---------------------------------------------------
//---- Top entity
module v51b9cf (
 input [31:0] v7d1d02,
 input [5:0] vaa5d49,
 input [5:0] v102134,
 input [5:0] v14eae6,
 input v4434b8,
 output [31:0] vc46106,
 output [31:0] vfab6dd
);

endmodule

//---------------------------------------------------
//-- Register
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- 
//---------------------------------------------------
//---- Top entity
module v625d79 (
 input [31:0] vc8ee55,
 input [31:0] v360926,
 input [5:0] vcd159e,
 output [31:0] vea2f6e
);

endmodule

//---------------------------------------------------
//-- ALU
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- 
//---------------------------------------------------
//---- Top entity
module vaa9caf (
 input [31:0] vcf12e3,
 input [25:0] vbaf620,
 input [31:0] v51b6bc,
 input v604d67,
 input va16ad8,
 output [31:0] va874ad
);

endmodule

//---------------------------------------------------
//-- Multiplexer1
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Multiplext Datan von der ALU, vom RAM und vom Immediate Operand
//---------------------------------------------------
//---- Top entity
module v1215e7 (
 input [31:0] ve0f1d2,
 output va34f84
);

endmodule

//---------------------------------------------------
//-- ErstesBit
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Gibt das erste (= niedrigste) Bit weiter
//---------------------------------------------------
//---- Top entity
module vef4843 (
 input [31:0] v3b6447,
 input [25:0] vb90512,
 input va1f8d5,
 input v301daf,
 output [31:0] ve4871c
);

endmodule

//---------------------------------------------------
//-- Multiplexer2
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Multiplext die möglichen ALU Eingänge (Register, kleiner und großer Immediate)
//---------------------------------------------------
//---- Top entity
module v433ce5 (
 input [31:0] v5a59b5,
 input [31:0] vb6adaf,
 input vf95e96,
 output [25:0] vbda1cf
);

endmodule

//---------------------------------------------------
//-- Multiplexer3
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Multiplext relative und absolute neue PCs. Die Bits 31 bis 26 werden ignoriert
//---------------------------------------------------
//---- Top entity
module v26af9a (
 input [25:0] v30c415,
 input [31:0] v5cb37b,
 input vb74a8b,
 output [31:0] v2cf625
);

endmodule

//---------------------------------------------------
//-- Multiplexer4
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Multiplext den aktuellen PC mit den Quelldaten2
//---------------------------------------------------
