// Code generated by Icestudio 0.10

`default_nettype none

//---- Top entity
module main (
 input [31:0] v7d1d02,
 input [5:0] vaa5d49,
 input [5:0] v102134,
 input [5:0] v14eae6,
 input v4434b8,
 input va1d41f,
 input v436420,
 output [31:0] vc46106,
 output [31:0] vfab6dd
);
 wire w0;
 wire [0:31] w1;
 assign w0 = va1d41f;
 assign w1 = v7d1d02;
 main_v56707c v56707c (
  .clock(w0),
  .re(w1)
 );
endmodule

//---------------------------------------------------
//-- Register
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- 
//---------------------------------------------------

module main_v56707c (
 input [31:0] re,
 input clock,
 output [31:0] regout
);
 reg [31:0] regout;
 
 always @(posedge clock) begin
     regout = re;
 end
endmodule
